### ISSUE TITLE
A couple of things regarding cocoa pods installation

### ISSUE THREAD

**Issue by rajohns08** [Skyvive/JsonObject#4]
1. **When installing without "use_frameworks!" in your cocoa pods file you get the following message:**
   - "[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it."
   - It might be worth mentioning to add that line to your podfile in the installation instructions.
2. **When installing with a platform of iOS 8.0 in my podfile, I get the following warning message:**
   - "[!] The platform of the target `JudgecardXSwift` (iOS 8.0) may not be compatible with `JsonObject (0.1.0)` which has a minimum requirement of iOS 8.3 - OS X 10.9."
   - But it still seems to work with my 8.0 platform version. 
3. **Also for people unfamiliar with cocoa pods it might be worth mentioning you will need to "import JsonObject" in files you want to use it. I normally don't have to import my classes that I write explicitly.**

**Comment by bradhilton** [comment]
Good points. I've updated the [README](https://github.com/Skyvive/JsonObject/blob/master/README.md) to address points 1 & 3. Thoughts?

It looks like I've already updated the [podspec](https://github.com/Skyvive/JsonObject/blob/master/JsonObject.podspec), so the next release will address the platform target issue.

**Comment by rajohns08** [comment]
Perfect, man!
